// Compile UNPRegistry.sol → write ABI + bytecode JSON used by the dashboard
const fs = require('fs');
const path = require('path');
const solc = require('solc');

const SRC_REG = path.join(__dirname, '..', 'contracts', 'UNPRegistry.sol');
const SRC_TOK = path.join(__dirname, '..', 'contracts', 'UNPToken.sol');
const SRC_STK = path.join(__dirname, '..', 'contracts', 'StakingContract.sol');
const SRC_PTR = path.join(__dirname, '..', 'contracts', 'APOSPointer.sol');
const SRC_ELN = path.join(__dirname, '..', 'contracts', 'ELNTST.sol');
const SRC_FCT = path.join(__dirname, '..', 'contracts', 'Faucet.sol');
const SRC_LB  = path.join(__dirname, '..', 'contracts', 'APOSLeaderboard.sol');
const OUT_REG = path.join(__dirname, 'apos-registry-build.json');
const OUT_TOK = path.join(__dirname, 'unp-token-build.json');
const OUT_STK = path.join(__dirname, 'staking-build.json');
const OUT_PTR = path.join(__dirname, 'apos-pointer-build.json');
const OUT_ELN = path.join(__dirname, 'elntst-build.json');
const OUT_FCT = path.join(__dirname, 'faucet-build.json');
const OUT_LB  = path.join(__dirname, 'leaderboard-build.json');

function compile(srcPath, contractName, outPath) {
  const source = fs.readFileSync(srcPath, 'utf8');
  const fname = path.basename(srcPath);
  const input = {
    language: 'Solidity',
    sources: { [fname]: { content: source } },
    settings: {
      // Pin to 'paris' so we don't emit PUSH0 (Shanghai). The chain spec
      // generated by the wizard does not enable EIP-3855, so PUSH0 in the
      // deployed bytecode would trigger BadInstruction at deploy time.
      evmVersion: 'paris',
      optimizer: { enabled: true, runs: 200 },
      outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'] } },
    },
  };
  const out = JSON.parse(solc.compile(JSON.stringify(input)));
  const errors = (out.errors || []).filter(e => e.severity === 'error');
  if (errors.length) {
    console.error('Compile errors in', fname);
    for (const e of errors) console.error(e.formattedMessage);
    process.exit(1);
  }
  const c = out.contracts[fname][contractName];
  fs.writeFileSync(outPath, JSON.stringify({
    abi: c.abi,
    bytecode: '0x' + c.evm.bytecode.object,
    compiledAt: new Date().toISOString(),
  }, null, 2));
  console.log(contractName, 'compiled. ABI:', c.abi.length, 'Bytecode bytes:', c.evm.bytecode.object.length / 2);
  console.log('  Wrote', outPath);
}

compile(SRC_REG, 'UNPRegistry', OUT_REG);
compile(SRC_TOK, 'UNPToken', OUT_TOK);
compile(SRC_STK, 'StakingContract', OUT_STK);
compile(SRC_PTR, 'APOSPointer', OUT_PTR);
compile(SRC_ELN, 'ELNTST', OUT_ELN);
compile(SRC_FCT, 'Faucet', OUT_FCT);
compile(SRC_LB,  'APOSLeaderboard', OUT_LB);
